[package]
edition = "2021"
name = "sphinx"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argon2 = "0.4.1"
k256 = {version = "0.11.4", feature = "arithmetic"}
rand = "0.8.5"
serde = "1.0.144"
sha3 = "0.10.4"
